---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: redirect
    app.kubernetes.io/part-of: services
    app.kubernetes.io/version: v0.99
  name: redirect
data:
  http.conf: |
        server {
                listen 80;
                server_name localhost;
                location /nginx_status {
                  stub_status;
                  allow 127.0.0.1;
                  deny all;
                }
        }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: redirect
    app.kubernetes.io/part-of: services
    app.kubernetes.io/version: v0.99
  name: redirect
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: broker
      app.kubernetes.io/name: redirect
      app.kubernetes.io/part-of: services
      app.kubernetes.io/version: v0.99
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: broker
        app.kubernetes.io/name: redirect
        app.kubernetes.io/part-of: services
        app.kubernetes.io/version: v0.99
    spec:
      volumes:
       - name: conf-volume
         configMap:
           name: redirect
           items:
             - key: http.conf
               path: http.conf
      containers:
      - name: my-redirect
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: conf-volume
      - image: nginx/nginx-prometheus-exporter:latest
        name: nginx-exporter
        args:
          - '-nginx.scrape-uri=http://localhost:80/nginx_status'
        ports:
          - containerPort: 9113
