---
apiVersion: v1
kind: Service
metadata:
  name: redirect-exposed
  labels:
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: redirect-exposed
    app.kubernetes.io/part-of: services
    app.kubernetes.io/version: v0.99
    metrics_exposed: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9113
      name: metrics
      protocol: TCP
      targetPort: 9113
  selector:
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: redirect
    app.kubernetes.io/part-of: services
    app.kubernetes.io/version: v0.99
