---
apiVersion: v1
kind: Service
metadata:
  name: redirect
  labels:
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: redirect
    app.kubernetes.io/part-of: services
    app.kubernetes.io/version: v0.99
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      name: http
    - port: 9113
      name: service-port
      protocol: TCP
      targetPort: 9113
  selector:
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: redirect
    app.kubernetes.io/part-of: services
    app.kubernetes.io/version: v0.99
