---
apiVersion: v1
kind: Service
metadata:
  name: awesome1
  labels:
    app.kubernetes.io/name: awesome1
    app.kubernetes.io/part-of: otherapp
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      name: http
    - port: 9113
      name: service-port
      protocol: TCP
      targetPort: 9113
  selector:
    app.kubernetes.io/name: awesome1
    app.kubernetes.io/part-of: otherapp
