---
apiVersion: v1
kind: Service
metadata:
  name: awesome1-exposed
  labels:
    app.kubernetes.io/name: awesome1
    app.kubernetes.io/part-of: otherapp
    metrics_exposed: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9113
      name: metrics
      protocol: TCP
      targetPort: 9113
  selector:
    app.kubernetes.io/name: awesome1
    app.kubernetes.io/part-of: otherapp
