---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: opalcbox
    component: web-server
    opal: opalcbox-pl
  name: opalcbox-pl
data:
  http.conf: |
    server {
            listen 80;
            server_name localhost;
            location /nginx_status {
              stub_status;
              allow 127.0.0.1;
              deny all;
            }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opalcbox
    component: web-server
    opal: opalcbox-pl
  name: opalcbox-pl
spec:
  selector:
    matchLabels:
      app: opalcbox
      component: web-server
      opal: opalcbox-pl
  replicas: 1
  template:
    metadata:
      labels:
        app: opalcbox
        component: web-server
        opal: opalcbox-pl
    spec:
      volumes:
        - name: conf-volume
          configMap:
            name: opalcbox-pl
            items:
              - key: http.conf
                path: http.conf
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: conf-volume
        - image: nginx/nginx-prometheus-exporter:latest
          name: nginx-exporter
          args:
            - "-nginx.scrape-uri=http://localhost:80/nginx_status"
          ports:
            - containerPort: 9113
