apiVersion: v1
kind: Service
metadata:
  name: opalcbox-pl
  labels:
    app: opalcbox
    component: web-server
    opal: opalcbox-pl
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 9777
      name: web
      protocol: TCP
      targetPort: 9113
  selector:
    app: opalcbox
    component: web-server
    opal: opalcbox-pl
