---
apiVersion: v1
kind: Service
metadata:
  name: opalcbox-pl-exposed
  labels:
    app: opalcbox
    opal: opalcbox-pl-exposed
    metrics_exposed: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9113
      name: metrics
      protocol: TCP
      targetPort: 9113
  selector:
    app: opalcbox
    component: web-server
    opal: opalcbox-pl
